Avoid using Java 8 `ConcurrentHashmap.newKeySet()`
It causes NoSuchMethodError because of https://stackoverflow.com/questions/64506917/using-concurrenthashmapnewkeyset-with-android-corelibrarydesugaring